apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb-payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb-payments
  template:
    metadata:
      labels:
        app: pgweb-payments
    spec:
      containers:
        - name: pgweb-payments
          image: sosedoff/pgweb
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
          env:
            - name: SESSIONS
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb-payments
  labels:
    app: pgweb-payments
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: pgweb-payments
  type: NodePort
