# PostgreSQL StatefulSet - ConfigMap
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql-payments
spec:
  serviceName: psql-payments-service
  selector:
    matchLabels:
      app: psql-payments
  replicas: 1
  template:
    metadata:
      labels:
        app: psql-payments
    spec:
      containers:
        - name: psql-payments
          image: postgres:latest
          volumeMounts:
            - name: psql-payments-disk
              mountPath: /data
          # Config from ConfigMap
          envFrom:
            - configMapRef:
                name: pqsl-payments-config
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: psql-payments-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---

# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-lb
spec:
  selector:
    app: psql-payments
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
      name: "db"
    - port: 443
      targetPort: 5432
      name: "https-to-db"
    - port: 8080
      targetPort: 5432
      name: "8080-to-db"
    - port: 80
      targetPort: 5432
      name: "tcp-to-db"

---

# PostgreSQL StatefulSet ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: pqsl-payments-config
  labels:
    app: psql-payments
data:
  POSTGRES_DB: payment
  POSTGRES_USER: generic
  POSTGRES_PASSWORD: changeme
  PGDATA: /data/pgdata
